#!/usr/bin/env perl

use v5.20.0;
use strict;
use warnings;
use Liguros::MEMinfo;


my $mem = Liguros::MEMinfo->new();

say $mem->mem_file;
say $mem->MemTotal;
say $mem->MemAvailable;
say $mem->MemFree;
say $mem->SwapTotal;
say $mem->SwapFree;

say $mem->get_json;
