#!/usr/bin/env perl

use v5.20.0;
use strict;
use warnings;
use Liguros::Report_Config;


my $report = Liguros::Report_Config->new();

say $report->config_location;
say $report->config_exists;
say $report->UUID;
say $report->kernel_info;
say $report->boot_dir_info;
say $report->installed_pkgs;
say $report->profile_info;
say $report->kit_info;
say $report->hardware_info;
